### ISSUE TITLE
Usage of EquivalencyAssertionOptions after upgrading from 3.0.107 and 4.2.1

### ISSUE THREAD

**Issue by tjrobinson** [dennisdoomen/FluentAssertions#353]
I'm having trouble finding any examples for rewriting this to work with 4.2.1 0 - can anyone help?

```
var defaultUserDetailsAssertionOptions = EquivalencyAssertionOptions<UserDetails>.Default;

EquivalencyAssertionOptions<UserDetails>.Default = () =>
{
	var config = defaultUserDetailsAssertionOptions();

	// Only compare the DateTime values to a reasonable level of precision as some is lost when round-tripped through BSON
	const string format = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffK";
	config.Using<DateTime>(ctx => ctx.Subject.ToString(format).Should().Be(ctx.Expectation.ToString(format)))
		.WhenTypeIs<DateTime>();

	return config;
};
```

The compilation error is: EquivalencyAssertionOptions<UserDetails>' does not contain a definition for 'Default'

**Comment by dennisdoomen** [comment]
It is replaced by the `AssertionOptions.AssertEquivalencyUsing` method. Check out the [unit tests](https://github.com/dennisdoomen/fluentassertions/blob/master/Tests/FluentAssertions.Shared.Specs/AssertionOptionSpecs.cs#L78) for some examples.

**Comment by tjrobinson** [comment]
Thanks @dennisdoomen - worked first time!

For reference, the new version of my code above is:

```
const string format = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffK";

// Only compare the DateTime values to a reasonable level of precision as some is lost when round-tripped through BSON
AssertionOptions.AssertEquivalencyUsing(options => options
	.Using<DateTime>(ctx => ctx.Subject.ToString(format).Should().Be(ctx.Expectation.ToString(format)))
	.WhenTypeIs<DateTime>());
```

**Comment by dennisdoomen** [comment]
:+1:
